package it.polimi.ingsw.utilities;

public enum GameControllerStates {
    PLAY_ASSISTANT, ASSISTANT_PLAYED, MOVE_STUDENT_1, MOVE_STUDENT_2, MOVE_STUDENT_3, MOVE_STUDENT_4, MOVE_MOTHER_NATURE, CHOOSE_CLOUD, END_TURN
}
