name: Maven test and package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode clean test package
      - uses: actions/upload-artifact@v3
        with:
          name: Eriantys - Client
          path: target/PSP02-client.jar
      - uses: actions/upload-artifact@v3
        with:
          name: Eriantys - Server
          path: target/PSP02-server.jar